# Generated by Django 5.1.15 on 2026-06-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("push", "Push")],
                        max_length=10,
                    ),
                ),
                ("recipient", models.CharField(max_length=200)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("template_code", models.CharField(blank=True, max_length=80)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=80, unique=True)),
                ("channel", models.CharField(max_length=10)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("locale", models.CharField(default="fr", max_length=5)),
            ],
        ),
    ]
