# Generated by Django 5.1.15 on 2026-06-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_imei", models.CharField(db_index=True, max_length=20)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("distance_km", models.FloatField(default=0)),
                ("duration_s", models.IntegerField(default=0)),
                ("max_speed", models.FloatField(default=0)),
                ("avg_speed", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(db_index=True)),
                ("device_imei", models.CharField(db_index=True, max_length=20)),
                ("type", models.CharField(max_length=50)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device_imei", "time"],
                        name="telemetry_d_device__a638df_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(db_index=True)),
                ("device_imei", models.CharField(db_index=True, max_length=20)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("speed", models.FloatField(default=0)),
                ("course", models.FloatField(default=0)),
                ("altitude", models.FloatField(default=0)),
                ("attributes", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["device_imei", "time"],
                        name="telemetry_p_device__14d03b_idx",
                    )
                ],
            },
        ),
    ]
