# Generated by Django 5.1.15 on 2026-06-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("enter", "Entrée zone"),
                            ("exit", "Sortie zone"),
                            ("overspeed", "Excès de vitesse"),
                            ("low_battery", "Batterie faible"),
                            ("sim_low_balance", "Crédit SIM faible"),
                        ],
                        max_length=20,
                    ),
                ),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("channels", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_imei", models.CharField(db_index=True, max_length=20)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("notified", models.BooleanField(default=False)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="geofencing.alertrule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("area", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofences",
                        to="crm.client",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alertrule",
            name="geofence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="geofencing.geofence",
            ),
        ),
    ]
