# Generated by Django 5.1.15 on 2026-06-09 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(blank=True, max_length=254)),
                ("action", models.CharField(max_length=50)),
                ("resource_type", models.CharField(blank=True, max_length=80)),
                ("resource_id", models.CharField(blank=True, max_length=80)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_audit_resourc_2a3aef_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_audit_user_id_a3c2bc_idx",
                    ),
                ],
            },
        ),
    ]
