# Generated by Django 5.1.15 on 2026-06-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_transaction_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="next_invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="period",
            field=models.CharField(
                choices=[
                    ("monthly", "Mensuel"),
                    ("quarterly", "Trimestriel"),
                    ("annual", "Annuel"),
                ],
                default="monthly",
                max_length=12,
            ),
        ),
    ]
