# Generated by Django 5.1.15 on 2026-06-09 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GpsUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imei", models.CharField(db_index=True, max_length=20, unique=True)),
                ("traccar_device_id", models.IntegerField(blank=True, null=True)),
                ("serial_number", models.CharField(blank=True, max_length=80)),
                ("brand", models.CharField(blank=True, max_length=60)),
                ("model_name", models.CharField(blank=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "En stock"),
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("maintenance", "En maintenance"),
                            ("terminated", "Résilié"),
                            ("inactive", "Inactif"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("installed_at", models.DateField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gps_units",
                        to="crm.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iccid", models.CharField(max_length=25, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("operator", models.CharField(blank=True, max_length=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspendue"),
                            ("inactive", "Inactive"),
                            ("pending", "En attente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("data_credit_mb", models.IntegerField(default=0)),
                ("activated_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sim_card",
                        to="fleet.gpsunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SimRecharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recharged_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sim_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recharges",
                        to="fleet.simcard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("plate", models.CharField(blank=True, max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("car", "Voiture"),
                            ("moto", "Moto"),
                            ("truck", "Camion"),
                            ("machine", "Engin"),
                            ("other", "Autre"),
                        ],
                        default="car",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="crm.client",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gpsunit",
            name="vehicle",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gps_unit",
                to="fleet.vehicle",
            ),
        ),
    ]
